# -*- coding: utf-8 -*-
"""Códigos PEX III

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cO5DRuuP8p1R41fZ2A6U2DnV98FBegrd
"""

import pandas as pd
import logging

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def profilename_financeiro(df):
    logging.info("Iniciando Data Profiling especializado...")

    if df.empty:
        logging.error("O DataFrame extraído está vazio.")
        return df

    # Validação de valores nulos
    nulos_valor = df['Valor'].isnull().sum()
    if nulos_valor > 0:
        logging.warning(f"Detectados {nulos_valor} registros sem valor.")

    # Verificação de datas
    # Como a coluna 'Dias' contém apenas o número do dia, vamos criar a data correta
    # Baseado no nome do arquivo 'gastos harpia 2026.xlsx'
    df['Data'] = pd.to_datetime(df['Data'].apply(lambda x: f"2026-01-{int(x):02d}" if pd.notnull(x) else x), errors='coerce')

    datas_invalidas = df['Data'].isnull().sum()
    if datas_invalidas > 0:
        logging.warning(f"Detectadas {datas_invalidas} datas inválidas.")

    # Duplicados
    duplicados = df.duplicated().sum()
    logging.info(f"Transações duplicadas identificadas: {duplicados}")

    print("\nResumo dos Dados Perfilados:")
    print(df.head())
    return df

# Carregamento da planilha
df_raw = pd.read_excel("gastos harpia 2026.xlsx", header=None)

# Localiza a linha que contém os cabeçalhos 'Dias' e 'Gastos'
header_row_idx = 0
for i, row in df_raw.iterrows():
    if 'Gastos' in row.values and 'Dias' in row.values:
        header_row_idx = i
        break

# Extração e Limpeza
df_temp = df_raw.copy()
df_temp.columns = df_raw.iloc[header_row_idx]
df_temp = df_temp.iloc[header_row_idx + 1:].reset_index(drop=True)

col_data = 'Dias'
col_valor = 'Gastos'

if col_data in df_temp.columns and col_valor in df_temp.columns:
    # Filtra apenas linhas onde há um dia definido e remove valores nulos de Gastos
    df_consolidado = df_temp[[col_data, col_valor]].copy()
    df_consolidado = df_consolidado.dropna(subset=[col_data])
    df_consolidado.columns = ['Data', 'Valor']
    df_consolidado['Descricao'] = "Transação Identificada"

    profilename_financeiro(df_consolidado)
else:
    print(f"Colunas não encontradas. Disponíveis: {df_temp.columns.tolist()}")

import logging

# Configuração do logging para o perfilamento
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s', force=True)

def profilename_financeiro_final(df):
    logging.info("--- Iniciando Data Profiling do Fluxo de Caixa (Harpia 2026) ---")

    # 1. Validação de valores nulos nas colunas críticas
    nulos_valor = df['Valor'].isnull().sum()
    if nulos_valor > 0:
        logging.warning(f"Alerta: Detectados {nulos_valor} registros sem valor monetário.")
    else:
        logging.info("Sucesso: Nenhum valor monetário nulo encontrado.")

    # 2. Verificação do padrão de datas
    # Como já tratamos a data na leitura, verificamos se a conversão resultou em NaT
    datas_invalidas = df['Data'].isnull().sum()
    if datas_invalidas > 0:
        logging.error(f"Erro: Inconsistência de tipo em {datas_invalidas} datas. Requer normalização ETL.")
    else:
        logging.info(f"Sucesso: Todas as {len(df)} datas foram validadas corretamente.")

    # 3. Análise de duplicidade de transação
    # Verifica se existem linhas idênticas para a mesma data, descrição e valor
    duplicados = df.duplicated(subset=['Data', 'Descricao', 'Valor']).sum()
    if duplicados > 0:
        logging.info(f"Aviso: Transações duplicadas identificadas: {duplicados}")
    else:
        logging.info("Sucesso: Nenhuma transação duplicada encontrada.")

    # 4. Sumário estatístico simples
    print("\n--- Estatísticas de Gastos ---")
    print(f"Total de Gastos no período: R$ {df['Valor'].astype(float).sum():.2f}")
    print(f"Maior gasto registrado: R$ {df['Valor'].astype(float).max():.2f}")

    return df

# Execução do Profiling usando os dados já carregados na célula anterior
# Certificamos que os tipos estão corretos para o pipeline
df_consolidado['Valor'] = pd.to_numeric(df_consolidado['Valor'], errors='coerce').fillna(0)
profiling_result = profilename_financeiro_final(df_consolidado)